name: Build iOS IPA for Sideloadly

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Ionic and dependencies
        run: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps

      - name: Install missing dependencies
        run: |
          npm install @ionic-native/core@latest @ionic-native/splash-screen@latest --legacy-peer-deps

      - name: Build Ionic app
        run: |
          ionic build

      - name: Sync Capacitor and install iOS dependencies
        run: |
          npx cap sync ios
          cd ios/App
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build Development IPA
        run: |
          cd ios/App
          rm -rf build Payload
          
          # Build with explicit code signing disabled for the build phase
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -derivedDataPath Build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build

          # Create IPA manually
          mkdir -p Payload
          mkdir -p build
          
          # Find the .app file (path might vary)
          if [ -d "Build/Build/Products/Debug-iphoneos/App.app" ]; then
            cp -r Build/Build/Products/Debug-iphoneos/App.app Payload/
          elif [ -d "Build/Products/Debug-iphoneos/App.app" ]; then
            cp -r Build/Products/Debug-iphoneos/App.app Payload/
          else
            echo "Looking for .app file..."
            find Build -name "*.app" -type d
            exit 1
          fi
          
          # Create IPA
          zip -r build/App.ipa Payload
          rm -rf Payload
          
          echo "IPA created at: ios/App/build/App.ipa"
          ls -la build/

      - name: Upload IPA for Sideloadly
        uses: actions/upload-artifact@v4
        with:
          name: ios-sideloadly-ipa
          path: ios/App/build/App.ipa