name: Build iOS (Unsigned IPA)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Ionic and dependencies
        run: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps

      - name: Install missing dependencies
        run: |
          npm install @ionic-native/core@latest @ionic-native/splash-screen@latest --legacy-peer-deps

      - name: Build Ionic app
        run: |
          ionic build

      - name: Sync Capacitor and install iOS dependencies
        run: |
          npx cap sync ios
          cd ios/App
          # Install CocoaPods if needed
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build unsigned IPA
        run: |
          cd ios/App
          
          # Clean previous builds
          rm -rf build

          # Create a development export options plist with manual signing
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string></string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string></string>
              <key>provisioningProfiles</key>
              <dict>
              </dict>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
          </dict>
          </plist>
          EOF

          # Build the archive with no code signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

          # Export the IPA without signing
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            -allowProvisioningUpdates \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: ios/App/build/**/*.ipa