name: Build iOS IPA for Sideloadly

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Ionic and dependencies
        run: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps

      - name: Install missing dependencies
        run: |
          npm install @ionic-native/core@latest @ionic-native/splash-screen@latest --legacy-peer-deps

      - name: Build Ionic app
        run: |
          ionic build

      - name: Sync Capacitor and install iOS dependencies
        run: |
          npx cap sync ios
          cd ios/App
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA for Sideloadly
        run: |
          cd ios/App
          
          # Clean previous builds
          rm -rf build

          # Build for development with proper entitlements
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            archive \
            DEVELOPMENT_TEAM="" \
            CODE_SIGN_IDENTITY="Apple Development" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGNING_ALLOWED=YES

          # Export with development method
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string></string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
              <key>iCloudContainerEnvironment</key>
              <string>Development</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            -allowProvisioningUpdates

      - name: Upload IPA for Sideloadly
        uses: actions/upload-artifact@v4
        with:
          name: ios-sideloadly-ipa
          path: ios/App/build/App.ipa