name: Build iOS IPA for Sideloadly

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Ionic and dependencies
        run: |
          npm install -g @ionic/cli
          npm install --legacy-peer-deps

      - name: Install missing dependencies
        run: |
          npm install @ionic-native/core@latest @ionic-native/splash-screen@latest --legacy-peer-deps

      - name: Build Ionic app
        run: |
          ionic build

      - name: Sync Capacitor and install iOS dependencies
        run: |
          npx cap sync ios
          cd ios/App
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build Development IPA
        run: |
          cd ios/App
          rm -rf build
          
          # Build directly as development IPA
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -derivedDataPath Build \
            DEVELOPMENT_TEAM="" \
            CODE_SIGNING_ALLOWED=YES \
            CODE_SIGN_STYLE="Manual" \
            build

          # Create IPA from the built app
          mkdir -p Payload
          cp -r Build/Build/Products/Debug-iphoneos/App.app Payload/
          zip -r build/App.ipa Payload
          rm -rf Payload

      - name: Upload IPA for Sideloadly
        uses: actions/upload-artifact@v4
        with:
          name: ios-sideloadly-ipa
          path: ios/App/build/App.ipa